# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: custom_options.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build(
  Google::Protobuf::FileDescriptor.new.tap do |f|
    f.syntax = :proto2
  end
) do
  add_message "pkg.MyOption" do
    optional :val, :int32, 1
  end
end

module Pkg
  MyOption = Google::Protobuf::DescriptorPool.generated_pool.lookup("pkg.MyOption").msgclass
end
