# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: custom_import.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build(
  Google::Protobuf::FileDescriptor.new.tap do |f|
    f.syntax = :proto2
  end
) do
  add_message "TestMessage" do
  end
end

TestMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("TestMessage").msgclass
