# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: generated_code_proto2.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build(
  Google::Protobuf::FileDescriptor.new.tap do |f|
    f.syntax = :proto2
  end
) do
  add_message "a.b.c.TestMessage" do
    optional :optional_int32, :int32, 1
    optional :optional_int64, :int64, 2
    required :required_int32, :int32, 3
  end
end

module A
  module B
    module C
      TestMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("a.b.c.TestMessage").msgclass
    end
  end
end
